name: inspre
description: A Flutter project to inspire people.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 3.1.0+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  rxdart: 0.20.0
  cloud_firestore: 0.12.9
  firebase_auth:  0.14.0+1
  google_sign_in: 3.2.4
  flutter_facebook_login: 1.2.0
  charts_flutter: ^0.4.0
  custom_chewie: ^0.7.0
  video_player: ^0.6.0
  cloud_functions: 0.0.5
  random_string: ^0.0.2
  firebase_storage: 3.0.5
  super_tooltip: ^0.9.0
  smooth_star_rating: 1.0.3
  sticky_headers: 0.1.8
  hidden_drawer_menu: ^1.0.1
  http: ^0.12.0
  shared_preferences: 0.4.3
  cached_network_image: ^1.0.0
  progress_indicators: ^0.1.2
  firebase_messaging: 2.1.0
  transparent_image: ^0.1.0
  flutter_advanced_networkimage: any
  image: 2.1.4
  swipedetector: 1.2.0
  firebase_analytics: 5.0.0
  flutter_share_social_media: 0.2.0
  image_picker_modern: 0.4.12+1
  camera: 0.5.2+2
  path_provider: 1.2.0
  image_gallery: 1.2.0
  feature_discovery: 0.4.1
  highlighter_coachmark: ^0.0.3
  flutter_launcher_icons: 0.7.2+1
  intl: 0.15.8
  url_launcher: 5.1.4
  

  
  
  
  
  
  

  


    
    


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon.png" 
  android: "launcher_icon"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/landscape.png
    - assets/group.png
    - assets/star1.jpeg
    - assets/calendar.png
    - assets/facebook.png
    - assets/flag.png
    - assets/login.png
    - assets/mountain.png
    - assets/plus.png
    - assets/rate.png
    - assets/review.png
    - assets/pic4.jpg
    - assets/rate.png
    - assets/goal.png
    - assets/pablo-basketball-game.png
    - assets/pablo-car-rental.png
    - assets/pablo-sign-in.png
    - assets/pablo-success-1.png
    - assets/pablo-uploading.png
    - assets/tara1.gif
    - assets/done.png
    - assets/ill1.png
    - assets/ill2.png
    - assets/ill3.png
    - assets/facebook.png
    - assets/google.png
    - assets/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
